name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Only for one python version to save on resources

      # Run black
      - name: black
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"
          src: "./dtaianomaly"

      # Install dtaianomaly (not required for black)
      - name: Install dtaianomaly
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
          pip list

      # Apply isort
      - name: isort
        uses: isort/isort-action@v1.1.1
        with:
          sortPaths: "dtaianomaly"
          configuration: "--check-only --diff --profile black"
