name: Unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string
      os:
        description: 'OS to use (i.e., the docker image)'
        required: true
        type: string

jobs:
  unit-test:
    runs-on: ${{ inputs.image || 'ubuntu-latest' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version || vars.DEFAULT_PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version || vars.DEFAULT_PYTHON_VERSION }}

    - name: Install dtaianomaly
      run: |
        python -m pip install --upgrade pip
        pip install .[tests,tqdm]
        pip list

    - name: Test with pytest
      run: pytest --cov=dtaianomaly --cov-report term-missing
